---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: korifi
spec:
  title: Korifi
  icon: https://github.com/cloudfoundry/korifi/raw/main/logo/color/Korifi-logo-icon-only-color.png
  statusInformers:
    - deployment/korifi-api-deployment
  ports:
    - serviceName: akorifi-api-svc
      servicePort: 443
      localPort: 8443
      applicationUrl: "https://korifi-api-svc"
